package com.ablackpikatchu.refinement.core.util.lists;

import com.ablackpikatchu.refinement.core.init.ItemInit;

import net.minecraft.item.Item;
import net.minecraft.item.Items;
import static net.minecraft.item.Items.*;

public class ItemLists {

	public static Item[] MOLDS = {
			ItemInit.GEM_MOLD.get(), ItemInit.INGOT_MOLD.get(), ItemInit.COGWHEEL_MOLD.get()
	};

	public static boolean isItemInTheList(Item[] items, Item item) {
		for (Item listItem : items) {
			if (listItem == item)
				return true;
		}
		return false;
	}

	public static boolean isMold(Item item) {
		return isItemInTheList(MOLDS, item);
	}

	public static Item[] DYES = {
			Items.BLACK_DYE, Items.BLUE_DYE, Items.BROWN_DYE, Items.CYAN_DYE, Items.GRAY_DYE, Items.GREEN_DYE,
			Items.LIGHT_BLUE_DYE, Items.LIGHT_GRAY_DYE, Items.LIME_DYE, Items.MAGENTA_DYE, Items.ORANGE_DYE,
			Items.PINK_DYE, Items.PURPLE_DYE, Items.RED_DYE, Items.WHITE_DYE, Items.YELLOW_DYE
	};

	public static Item[] LOGS = {
			Items.OAK_LOG, Items.ACACIA_LOG, Items.BIRCH_LOG, Items.DARK_OAK_LOG, Items.JUNGLE_LOG, Items.SPRUCE_LOG
	};
	
	public static Item[] LEAVES = {
			Items.OAK_LEAVES, Items.ACACIA_LEAVES, Items.BIRCH_LEAVES, Items.DARK_OAK_LEAVES, Items.JUNGLE_LEAVES, Items.SPRUCE_LEAVES
	};

	public static Item[] GLASS = {
			Items.GLASS, Items.BLACK_STAINED_GLASS, Items.BLUE_STAINED_GLASS, Items.BROWN_STAINED_GLASS,
			Items.CYAN_STAINED_GLASS, Items.GRAY_STAINED_GLASS, Items.GREEN_STAINED_GLASS,
			Items.LIGHT_BLUE_STAINED_GLASS, Items.LIGHT_GRAY_STAINED_GLASS, Items.LIME_STAINED_GLASS,
			Items.MAGENTA_STAINED_GLASS, Items.ORANGE_STAINED_GLASS, Items.PINK_STAINED_GLASS,
			Items.PURPLE_STAINED_GLASS, Items.RED_STAINED_GLASS, Items.WHITE_STAINED_GLASS, Items.YELLOW_STAINED_GLASS
	};

	public static Item[] CONCRETE_POWDERS = {
			Items.BLACK_CONCRETE_POWDER, Items.BLUE_CONCRETE_POWDER, Items.BROWN_CONCRETE_POWDER,
			Items.CYAN_CONCRETE_POWDER, Items.GRAY_CONCRETE_POWDER, Items.GREEN_CONCRETE_POWDER,
			Items.LIGHT_BLUE_CONCRETE_POWDER, Items.LIGHT_GRAY_CONCRETE_POWDER, Items.LIME_CONCRETE_POWDER,
			Items.MAGENTA_CONCRETE_POWDER, Items.ORANGE_CONCRETE_POWDER, Items.PINK_CONCRETE_POWDER,
			Items.PURPLE_CONCRETE_POWDER, Items.RED_CONCRETE_POWDER, Items.WHITE_CONCRETE_POWDER,
			Items.YELLOW_CONCRETE_POWDER
	};

	public static Item[] CONCRETES = {
			Items.BLACK_CONCRETE, Items.BLUE_CONCRETE, Items.BROWN_CONCRETE, Items.CYAN_CONCRETE, Items.GRAY_CONCRETE,
			Items.GREEN_CONCRETE, Items.LIGHT_BLUE_CONCRETE, Items.LIGHT_GRAY_CONCRETE, Items.LIME_CONCRETE,
			Items.MAGENTA_CONCRETE, Items.ORANGE_CONCRETE, Items.PINK_CONCRETE, Items.PURPLE_CONCRETE,
			Items.RED_CONCRETE, Items.WHITE_CONCRETE, Items.YELLOW_CONCRETE
	};

	public static Item[] WOOLS = {
			Items.BLACK_WOOL, Items.BLUE_WOOL, Items.BROWN_WOOL, Items.CYAN_WOOL, Items.GRAY_WOOL, Items.GREEN_WOOL,
			Items.LIGHT_BLUE_WOOL, Items.LIGHT_GRAY_WOOL, Items.LIME_WOOL, Items.MAGENTA_WOOL, Items.ORANGE_WOOL,
			Items.PINK_WOOL, Items.PURPLE_WOOL, Items.RED_WOOL, Items.WHITE_WOOL, Items.YELLOW_WOOL
	};

	public static Item[] TERRACOTTAS = {
			TERRACOTTA, Items.BLACK_TERRACOTTA, Items.BLUE_TERRACOTTA, Items.BROWN_TERRACOTTA, Items.CYAN_TERRACOTTA,
			Items.GRAY_TERRACOTTA, Items.GREEN_TERRACOTTA, Items.LIGHT_BLUE_TERRACOTTA, Items.LIGHT_GRAY_TERRACOTTA,
			Items.LIME_TERRACOTTA, Items.MAGENTA_TERRACOTTA, Items.ORANGE_TERRACOTTA, Items.PINK_TERRACOTTA,
			Items.PURPLE_TERRACOTTA, Items.RED_TERRACOTTA, Items.WHITE_TERRACOTTA, Items.YELLOW_TERRACOTTA
	};

	public static Item[] STONES = {
			COBBLESTONE, STONE, STONE_BRICKS, ANDESITE, DIORITE, BLACKSTONE, GRANITE, BASALT, END_STONE,
			MOSSY_COBBLESTONE, MOSSY_STONE_BRICKS, SMOOTH_STONE, NETHERRACK
	};

	public static Item[] NON_WOOD_STAIRS = {
			Items.ANDESITE_STAIRS, Items.BLACKSTONE_STAIRS, Items.BRICK_STAIRS, Items.COBBLESTONE_STAIRS,
			Items.DARK_PRISMARINE_STAIRS, Items.DIORITE_STAIRS, Items.END_STONE_BRICK_STAIRS, Items.GRANITE_STAIRS,
			Items.MOSSY_COBBLESTONE_STAIRS, Items.MOSSY_STONE_BRICK_STAIRS, Items.NETHER_BRICK_STAIRS,
			Items.POLISHED_ANDESITE_STAIRS, Items.POLISHED_BLACKSTONE_BRICK_STAIRS, Items.POLISHED_BLACKSTONE_STAIRS,
			Items.POLISHED_DIORITE_STAIRS, Items.POLISHED_GRANITE_STAIRS, Items.PRISMARINE_BRICK_STAIRS,
			Items.PRISMARINE_STAIRS, Items.PURPUR_STAIRS, Items.QUARTZ_STAIRS, Items.RED_NETHER_BRICK_STAIRS,
			Items.RED_SANDSTONE_STAIRS, Items.SANDSTONE_STAIRS, Items.SMOOTH_QUARTZ_STAIRS,
			Items.SMOOTH_RED_SANDSTONE_STAIRS, Items.SMOOTH_SANDSTONE_STAIRS, Items.STONE_BRICK_STAIRS,
			Items.STONE_STAIRS
	};

	public static Item[] NON_WOOD_SLABS = {
			Items.ANDESITE_SLAB, Items.BLACKSTONE_SLAB, Items.BRICK_SLAB, Items.COBBLESTONE_SLAB,
			Items.DARK_PRISMARINE_SLAB, Items.DIORITE_SLAB, Items.END_STONE_BRICK_SLAB, Items.GRANITE_STAIRS,
			Items.MOSSY_COBBLESTONE_STAIRS, Items.MOSSY_STONE_BRICK_STAIRS, Items.NETHER_BRICK_SLAB,
			Items.POLISHED_ANDESITE_SLAB, Items.POLISHED_BLACKSTONE_BRICK_SLAB, Items.POLISHED_BLACKSTONE_SLAB,
			Items.POLISHED_DIORITE_SLAB, Items.POLISHED_GRANITE_SLAB, Items.PRISMARINE_BRICK_SLAB,
			Items.PRISMARINE_SLAB, Items.PURPUR_SLAB, Items.QUARTZ_SLAB, Items.RED_NETHER_BRICK_SLAB,
			Items.RED_SANDSTONE_SLAB, Items.SANDSTONE_SLAB, Items.SMOOTH_QUARTZ_SLAB, Items.SMOOTH_RED_SANDSTONE_SLAB,
			Items.SMOOTH_SANDSTONE_SLAB, Items.STONE_BRICK_SLAB, Items.STONE_SLAB
	};

}
