modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/ABlackPikatchu/Refinement/issues"
[[mods]]
modId="refinement"
version="${file.jarVersion}"
displayName="Refinement"
displayURL="https://github.com/ABlackPikatchu/Refinement"
logoFile="refinement_logo.png"
credits="Thanks to the Refinement Dev team for all the hard work!"
authors="ABlackPikatchu, matyrobbrt and True Penut"
description='''
Refinement is a mod that adds several new materials, tools, armors and machines.
'''
[[dependencies.refinement]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.refinement]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.refinement]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
